# Generated by Django 3.2.4 on 2021-07-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
