# Generated by Django 3.2.4 on 2021-06-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_rename_userfollows_userfollow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
