# Generated by Django 3.2.4 on 2021-07-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_ticket_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='wishlisted',
            field=models.BooleanField(default=False),
        ),
    ]
